  <!-- 
    PHP version 7
  @author      Webjump Core Team <dev@webjump.com.br>
  @copyright   2021 Webjump (http://www.webjump.com.br)
  @license     http://www.webjump.com.br  Copyright
  @link        http://www.webjump.com.br 
-->

<?php

/** @var $block Magento\Framework\View\Element\Template */
$baseUrl = $block->getBaseUrl();
?>
<section class="custom-block-container">
    <p class="custom-block-url"><?= $baseUrl ?></p>
</section>